name: Mod request
description: Suggest a new mod to be added or replaced in Dawncraft
labels: mod
body:
- type: markdown
  attributes:
    value: |
      ## Mod name ⤴️
      Before you request a mod, [please search](https://github.com/dawncraft-modpack/dawncraft-workspace/issues) if it has already been requested.

- type: input
  attributes:
    label: CurseForge link
    description: If you know the link, please write it. If you don't know the link, do you know the dev's stance? (e.g. pending approval, planned, considering, not considering, etc.)
    placeholder: https://www.curseforge.com/minecraft/mc-mods/...
  validations:
    required: true
      
- type: dropdown
  attributes:
    label: CurseForge Mod Distribution
    multiple: false
    options:
      - Unknown
      - Allowed
      - Not allowed
  validations:
    required: true
    
- type: markdown
  attributes:
    value: |
      1. Go to https://cflookup.com
      2. Paste the mod link to "Project Id / Slug" and click `Search project`
      3. Look at the `Mod Distribution` value and select it above

- type: input
  attributes:
    label: Source/other link
    description: For example, a GitHub repository. Optional.
    placeholder: https://...
  validations:
    required: false

- type: dropdown
  attributes:
    label: License
    description: Can be found on CurseForge, Modrinth and GitHub sidebar. If you only have a GitHub link and you can't find it from the sidebar, it is ARR.
    options:
      - All Rights Reserved / ARR
      - (any other license)
  validations:
    required: true

- type: textarea
  attributes:
    label: What it does
    description: A short description of what the mod does. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be in the modpack
    description: How can the change benefit everyone?
  validations:
    required: true

- type: textarea
  attributes:
    label: Why shouldn't it be in the modpack
    description: Don't forget to include any downsides of the mod, you know every mod has some.
    placeholder: |
      Examples: not available in CurseForge, still in beta, depends on something, has confusing settings.
  validations:
      required: true
    
- type: textarea
  attributes:
    label: Additional details
    description: Anything else you want to add?
  validations:
    required: false
